name: CI
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        uses: npm install

      - name: Build project
        run: npm run build

      - name: Checkout typescript errors
        run : npm i -g typescript && tsc

      - name: Checkout lint errors
        run : npm run eslint 

      - name: Launch unit ant Integration tests
        run : npm run test
        